# Generated by Django 6.0.5 on 2026-05-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон, факс')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('address', models.TextField(verbose_name='Физический адрес для встреч и почты')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Фидбэк', 'verbose_name_plural': 'Фидбэки'},
        ),
    ]
